# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/AuditEvent/AuthorizeEvent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/AuditEvent/AuthorizeEvent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(Protobuf/AuditEvent/AuthorizeEvent.proto\x12&ClassIsland.Shared.Protobuf.AuditEvent\"\x1f\n\x0e\x41uthorizeEvent\x12\r\n\x05Level\x18\x01 \x01(\x05\x42)\xaa\x02&ClassIsland.Shared.Protobuf.AuditEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.AuditEvent.AuthorizeEvent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002&ClassIsland.Shared.Protobuf.AuditEvent'
  _globals['_AUTHORIZEEVENT']._serialized_start=84
  _globals['_AUTHORIZEEVENT']._serialized_end=115
# @@protoc_insertion_point(module_scope)
