# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/AuditEvent/ProfileItemUpdated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/AuditEvent/ProfileItemUpdated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Enum import ListItemUpdateOperations_pb2 as Protobuf_dot_Enum_dot_ListItemUpdateOperations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,Protobuf/AuditEvent/ProfileItemUpdated.proto\x12&ClassIsland.Shared.Protobuf.AuditEvent\x1a,Protobuf/Enum/ListItemUpdateOperations.proto\"s\n\x12ProfileItemUpdated\x12\x0e\n\x06ItemId\x18\x01 \x01(\t\x12M\n\tOperation\x18\x02 \x01(\x0e\x32:.ClassIsland.Shared.Protobuf.Enum.ListItemUpdateOperationsB)\xaa\x02&ClassIsland.Shared.Protobuf.AuditEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.AuditEvent.ProfileItemUpdated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002&ClassIsland.Shared.Protobuf.AuditEvent'
  _globals['_PROFILEITEMUPDATED']._serialized_start=134
  _globals['_PROFILEITEMUPDATED']._serialized_end=249
# @@protoc_insertion_point(module_scope)
