# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Service/Audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Service/Audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Client import AuditScReq_pb2 as Protobuf_dot_Client_dot_AuditScReq__pb2
from core.proto_gen.Protobuf.Server import AuditScRsp_pb2 as Protobuf_dot_Server_dot_AuditScRsp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cProtobuf/Service/Audit.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a Protobuf/Client/AuditScReq.proto\x1a Protobuf/Server/AuditScRsp.proto2s\n\x05\x41udit\x12j\n\x08LogEvent\x12..ClassIsland.Shared.Protobuf.Client.AuditScReq\x1a..ClassIsland.Shared.Protobuf.Server.AuditScRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Service.Audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Service'
  _globals['_AUDIT']._serialized_start=137
  _globals['_AUDIT']._serialized_end=252
# @@protoc_insertion_point(module_scope)
