# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Service/ConfigUpload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Service/ConfigUpload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Server import ConfigUploadScRsp_pb2 as Protobuf_dot_Server_dot_ConfigUploadScRsp__pb2
from core.proto_gen.Protobuf.Client import ConfigUploadScReq_pb2 as Protobuf_dot_Client_dot_ConfigUploadScReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Protobuf/Service/ConfigUpload.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a\'Protobuf/Server/ConfigUploadScRsp.proto\x1a\'Protobuf/Client/ConfigUploadScReq.proto2\x8c\x01\n\x0c\x43onfigUpload\x12|\n\x0cUploadConfig\x12\x35.ClassIsland.Shared.Protobuf.Client.ConfigUploadScReq\x1a\x35.ClassIsland.Shared.Protobuf.Server.ConfigUploadScRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Service.ConfigUpload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Service'
  _globals['_CONFIGUPLOAD']._serialized_start=159
  _globals['_CONFIGUPLOAD']._serialized_end=299
# @@protoc_insertion_point(module_scope)
