# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto_gen.Protobuf.Client import HandshakeScReq_pb2 as Protobuf_dot_Client_dot_HandshakeScReq__pb2
from core.proto_gen.Protobuf.Server import HandshakeScRsp_pb2 as Protobuf_dot_Server_dot_HandshakeScRsp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Protobuf/Service/Handshake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandshakeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginHandshake = channel.unary_unary(
                '/ClassIsland.Shared.Protobuf.Service.Handshake/BeginHandshake',
                request_serializer=Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScBeginHandShakeReq.SerializeToString,
                response_deserializer=Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScBeginHandShakeRsp.FromString,
                _registered_method=True)
        self.CompleteHandshake = channel.unary_unary(
                '/ClassIsland.Shared.Protobuf.Service.Handshake/CompleteHandshake',
                request_serializer=Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScCompleteHandshakeReq.SerializeToString,
                response_deserializer=Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScCompleteHandshakeRsp.FromString,
                _registered_method=True)


class HandshakeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BeginHandshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteHandshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandshakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginHandshake,
                    request_deserializer=Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScBeginHandShakeReq.FromString,
                    response_serializer=Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScBeginHandShakeRsp.SerializeToString,
            ),
            'CompleteHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteHandshake,
                    request_deserializer=Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScCompleteHandshakeReq.FromString,
                    response_serializer=Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScCompleteHandshakeRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassIsland.Shared.Protobuf.Service.Handshake', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ClassIsland.Shared.Protobuf.Service.Handshake', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Handshake(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeginHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClassIsland.Shared.Protobuf.Service.Handshake/BeginHandshake',
            Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScBeginHandShakeReq.SerializeToString,
            Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScBeginHandShakeRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClassIsland.Shared.Protobuf.Service.Handshake/CompleteHandshake',
            Protobuf_dot_Client_dot_HandshakeScReq__pb2.HandshakeScCompleteHandshakeReq.SerializeToString,
            Protobuf_dot_Server_dot_HandshakeScRsp__pb2.HandshakeScCompleteHandshakeRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
