# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Service/Handshake.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Service/Handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Client import HandshakeScReq_pb2 as Protobuf_dot_Client_dot_HandshakeScReq__pb2
from core.proto_gen.Protobuf.Server import HandshakeScRsp_pb2 as Protobuf_dot_Server_dot_HandshakeScRsp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n Protobuf/Service/Handshake.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a$Protobuf/Client/HandshakeScReq.proto\x1a$Protobuf/Server/HandshakeScRsp.proto2\xc2\x02\n\tHandshake\x12\x94\x01\n\x0e\x42\x65ginHandshake\x12@.ClassIsland.Shared.Protobuf.Client.HandshakeScBeginHandShakeReq\x1a@.ClassIsland.Shared.Protobuf.Server.HandshakeScBeginHandShakeRsp\x12\x9d\x01\n\x11\x43ompleteHandshake\x12\x43.ClassIsland.Shared.Protobuf.Client.HandshakeScCompleteHandshakeReq\x1a\x43.ClassIsland.Shared.Protobuf.Server.HandshakeScCompleteHandshakeRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Service.Handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Service'
  _globals['_HANDSHAKE']._serialized_start=150
  _globals['_HANDSHAKE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
