# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Server/HandshakeScRsp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Server/HandshakeScRsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Enum import Retcode_pb2 as Protobuf_dot_Enum_dot_Retcode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$Protobuf/Server/HandshakeScRsp.proto\x12\"ClassIsland.Shared.Protobuf.Server\x1a\x1bProtobuf/Enum/Retcode.proto\"\xa5\x01\n\x1cHandshakeScBeginHandShakeRsp\x12:\n\x07Retcode\x18\x01 \x01(\x0e\x32).ClassIsland.Shared.Protobuf.Enum.Retcode\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x1f\n\x17\x43hallengeTokenDecrypted\x18\x03 \x01(\t\x12\x17\n\x0fServerPublicKey\x18\x04 \x01(\t\"\x81\x01\n\x1fHandshakeScCompleteHandshakeRsp\x12:\n\x07Retcode\x18\x01 \x01(\x0e\x32).ClassIsland.Shared.Protobuf.Enum.Retcode\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x11\n\tSessionId\x18\x03 \x01(\tB%\xaa\x02\"ClassIsland.Shared.Protobuf.Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Server.HandshakeScRsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Server'
  _globals['_HANDSHAKESCBEGINHANDSHAKERSP']._serialized_start=106
  _globals['_HANDSHAKESCBEGINHANDSHAKERSP']._serialized_end=271
  _globals['_HANDSHAKESCCOMPLETEHANDSHAKERSP']._serialized_start=274
  _globals['_HANDSHAKESCCOMPLETEHANDSHAKERSP']._serialized_end=403
# @@protoc_insertion_point(module_scope)
