# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Enum/AuditEvents.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Enum/AuditEvents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fProtobuf/Enum/AuditEvents.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x98\x02\n\x0b\x41uditEvents\x12\x10\n\x0c\x44\x65\x66\x61ultEvent\x10\x00\x12\x14\n\x10\x41uthorizeSuccess\x10\x01\x12\x13\n\x0f\x41uthorizeFailed\x10\x02\x12\x16\n\x12\x41ppSettingsUpdated\x10\x04\x12\x18\n\x14\x43lassChangeCompleted\x10\x05\x12\x14\n\x10\x43lassPlanUpdated\x10\x06\x12\x15\n\x11TimeLayoutUpdated\x10\x07\x12\x12\n\x0eSubjectUpdated\x10\x08\x12\x0e\n\nAppCrashed\x10\t\x12\x0e\n\nAppStarted\x10\n\x12\r\n\tAppExited\x10\x0b\x12\x13\n\x0fPluginInstalled\x10\x0c\x12\x15\n\x11PluginUninstalled\x10\rB#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Enum.AuditEvents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 ClassIsland.Shared.Protobuf.Enum'
  _globals['_AUDITEVENTS']._serialized_start=70
  _globals['_AUDITEVENTS']._serialized_end=350
# @@protoc_insertion_point(module_scope)
