# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Enum/ConfigTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Enum/ConfigTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fProtobuf/Enum/ConfigTypes.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x89\x01\n\x0b\x43onfigTypes\x12\x15\n\x11UnspecifiedConfig\x10\x00\x12\x0f\n\x0b\x41ppSettings\x10\x01\x12\x0b\n\x07Profile\x10\x02\x12\x14\n\x10\x43urrentComponent\x10\x03\x12\x15\n\x11\x43urrentAutomation\x10\x04\x12\x08\n\x04Logs\x10\x05\x12\x0e\n\nPluginList\x10\x06\x42#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Enum.ConfigTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 ClassIsland.Shared.Protobuf.Enum'
  _globals['_CONFIGTYPES']._serialized_start=70
  _globals['_CONFIGTYPES']._serialized_end=207
# @@protoc_insertion_point(module_scope)
