# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Enum/ListItemUpdateOperations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Enum/ListItemUpdateOperations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,Protobuf/Enum/ListItemUpdateOperations.proto\x12 ClassIsland.Shared.Protobuf.Enum*L\n\x18ListItemUpdateOperations\x12\x0f\n\x0bUnspecified\x10\x00\x12\x07\n\x03\x41\x64\x64\x10\x01\x12\n\n\x06Update\x10\x02\x12\n\n\x06Remove\x10\x03\x42#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Enum.ListItemUpdateOperations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 ClassIsland.Shared.Protobuf.Enum'
  _globals['_LISTITEMUPDATEOPERATIONS']._serialized_start=82
  _globals['_LISTITEMUPDATEOPERATIONS']._serialized_end=158
# @@protoc_insertion_point(module_scope)
