# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Command/GetClientConfig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Command/GetClientConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Enum import ConfigTypes_pb2 as Protobuf_dot_Enum_dot_ConfigTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&Protobuf/Command/GetClientConfig.proto\x12#ClassIsland.Shared.Protobuf.Command\x1a\x1fProtobuf/Enum/ConfigTypes.proto\"i\n\x0fGetClientConfig\x12\x13\n\x0bRequestGuid\x18\x01 \x01(\t\x12\x41\n\nConfigType\x18\x02 \x01(\x0e\x32-.ClassIsland.Shared.Protobuf.Enum.ConfigTypesB&\xaa\x02#ClassIsland.Shared.Protobuf.Commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Command.GetClientConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Command'
  _globals['_GETCLIENTCONFIG']._serialized_start=112
  _globals['_GETCLIENTCONFIG']._serialized_end=217
# @@protoc_insertion_point(module_scope)
