# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Client/AuditScReq.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Client/AuditScReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto_gen.Protobuf.Enum import AuditEvents_pb2 as Protobuf_dot_Enum_dot_AuditEvents__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n Protobuf/Client/AuditScReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\x1a\x1fProtobuf/Enum/AuditEvents.proto\"q\n\nAuditScReq\x12<\n\x05\x45vent\x18\x01 \x01(\x0e\x32-.ClassIsland.Shared.Protobuf.Enum.AuditEvents\x12\x0f\n\x07Payload\x18\x02 \x01(\x0c\x12\x14\n\x0cTimestampUtc\x18\x03 \x01(\x03\x42%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Client.AuditScReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Client'
  _globals['_AUDITSCREQ']._serialized_start=105
  _globals['_AUDITSCREQ']._serialized_end=218
# @@protoc_insertion_point(module_scope)
