# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Client/ConfigUploadScReq.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Client/ConfigUploadScReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'Protobuf/Client/ConfigUploadScReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\";\n\x11\x43onfigUploadScReq\x12\x15\n\rRequestGuidId\x18\x01 \x01(\t\x12\x0f\n\x07Payload\x18\x02 \x01(\tB%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Client.ConfigUploadScReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Client'
  _globals['_CONFIGUPLOADSCREQ']._serialized_start=79
  _globals['_CONFIGUPLOADSCREQ']._serialized_end=138
# @@protoc_insertion_point(module_scope)
