# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Client/HandshakeScReq.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protobuf/Client/HandshakeScReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$Protobuf/Client/HandshakeScReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\"\x83\x01\n\x1cHandshakeScBeginHandShakeReq\x12\x11\n\tClientUid\x18\x01 \x01(\t\x12\x11\n\tClientMac\x18\x02 \x01(\t\x12\x1f\n\x17\x43hallengeTokenEncrypted\x18\x03 \x01(\t\x12\x1c\n\x14RequestedServerKeyId\x18\x04 \x01(\x03\"3\n\x1fHandshakeScCompleteHandshakeReq\x12\x10\n\x08\x41\x63\x63\x65pted\x18\x01 \x01(\x08\x42%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Client.HandshakeScReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Client'
  _globals['_HANDSHAKESCBEGINHANDSHAKEREQ']._serialized_start=77
  _globals['_HANDSHAKESCBEGINHANDSHAKEREQ']._serialized_end=208
  _globals['_HANDSHAKESCCOMPLETEHANDSHAKEREQ']._serialized_start=210
  _globals['_HANDSHAKESCCOMPLETEHANDSHAKEREQ']._serialized_end=261
# @@protoc_insertion_point(module_scope)
